#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

TOTAL_STAGES=8
TOTAL_MINUTES=15

banner "Waveger — local setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites" 2
say "Waveger needs Node 24+, pnpm 11+, and the Vercel CLI."

node_major=$(node -v 2>/dev/null | sed 's/^v\([0-9]*\).*/\1/' || echo 0)
if [[ "${node_major:-0}" -ge 24 ]]; then
  say "node $(node -v) ✓"
else
  warn "Node 24+ not found (found: $(node -v 2>/dev/null || echo none))."
  open_url "https://nodejs.org/en/download"
  step "Install Node 24 or newer, then re-run this script."
  exit 1
fi

if command -v pnpm >/dev/null 2>&1; then
  say "pnpm $(pnpm -v) ✓"
else
  step "Enabling pnpm through corepack."
  corepack enable || {
    warn "corepack failed. Install pnpm yourself: https://pnpm.io/installation"
    exit 1
  }
fi

if command -v vercel >/dev/null 2>&1; then
  say "vercel $(vercel --version 2>/dev/null | tail -1) ✓"
else
  step "Installing the Vercel CLI globally."
  pnpm add -g vercel
fi

pause "Prerequisites look good. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to Vercel" 2
say "Every secret this project needs is injected by Vercel (ADR 0008)."
say "Nothing below is copied by hand, which is why this step exists."

if vercel whoami >/dev/null 2>&1; then
  say "already signed in as $(vercel whoami 2>/dev/null)"
else
  step "A browser window will open. Sign in, then come back here."
  vercel login
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Link this checkout to the Vercel project" 2
say "Project 'waveger', team 'jacobreesnew-7380s-projects'."

if [[ -f .vercel/project.json ]]; then
  say "already linked ✓"
else
  step "Answer 'yes' to linking, then pick the existing 'waveger' project."
  step "Do NOT create a new project — the database hangs off the existing one."
  vercel link
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Pull the environment" 2
say "Neon sets sixteen variables on the project. Two of them matter:"
note "  DATABASE_URL           pooled   — what the app uses"
note "  DATABASE_URL_UNPOOLED  direct   — what migrations and tests use"

vercel env pull .env.local

for required in DATABASE_URL DATABASE_URL_UNPOOLED; do
  if grep -qE "^${required}=" .env.local; then
    say "$required ✓"
  else
    warn "$required is missing from .env.local."
    step "Check the Neon integration is still attached to the project, then re-run."
    exit 1
  fi
done

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Install dependencies" 3
say "One install covers both apps and every shared package."
pnpm install

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Apply the migrations" 1
say "Hand-written SQL, applied in order, recorded in schema_migration."
say "Safe to re-run: already-applied migrations are skipped."
pnpm db:migrate

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Point the native app at the API" 2
say "The native app calls the same API the web app serves."
say "On a simulator that is your machine; on a real device it is your LAN IP."
say "Leave this blank to let the app derive it from the Metro server."

ENV_FILE="apps/native/.env.local"
ask EXPO_PUBLIC_API_URL "API base URL (e.g. http://localhost:3000, or blank):"
if [[ -n "${EXPO_PUBLIC_API_URL:-}" ]]; then
  write_env EXPO_PUBLIC_API_URL "$EXPO_PUBLIC_API_URL"
else
  note "skipped — the app will use the Metro host and port 3000"
fi
ENV_FILE=".env.local"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check it works" 1
say "The suite runs against the real database you just migrated."
if pnpm test; then
  say "green ✓"
else
  warn "the suite failed — the setup above is done, but something is wrong"
  SKIPPED+=("investigate the failing test suite")
fi

finish
note "next: 'pnpm dev' for the web app, 'pnpm dev:native' for the native one"
note "in an Orca worktree, start Expo with: pnpm expo start --port \$RCT_METRO_PORT"
printf '\n'
